### ISSUE TITLE
请问能共享下ChinaDNS修改后的源码吗？

### ISSUE THREAD

**Issue by adolink** [izerosoul/shadowsocks_erx#1]
我自己用的是ERL，是mips所以不能直接使用，其他程序都是自己编译好后替换的，但是ChinaDNS只能用原版有BUG的版本。

**Comment by izerosoul** [comment]
源码已上传到网盘哈：

http://pan.baidu.com/s/1o8yL2e2
https://mega.nz/#!aJdVTShZ!yVlx42om2w7mkHnxK_1nZ7-2J0DoZoHaXpCbFtLsMhE
两个链接文件相同，从哪下都可以

**Comment by adolink** [comment]
感激，已经编译好使用中
