### ISSUE TITLE
SS开启后网速回到十年前 

### ISSUE THREAD

**Issue by nimotsang** [izerosoul/shadowsocks_erx#25]
家里的宽带是500M，之前家人和我说看爱奇艺等国内的视频网站有时候会卡我没当回事，我最近发现一个问题，原来我的SS开启后好像变成了全局模式，上Speedtest IP变成了香港的，速度只有50M，只要关闭测速就正常，所以我怀疑是不是开了SS导致看视频卡的问题，我有想过把不需要翻墙的机器或者盒子设置成Bypass的网段，但是原来我记得很早之前SS开起来后也不会影响我的测速，这是不是设置的问题，谢谢您。

**Comment by izerosoul** [comment]
speedtest服务器IP是美国的，你访问的时候肯定会自动使用ss访问，导致speedtest识别为你是香港的用户，所以会用香港节点测速。
http://tool.chinaz.com/dns/?type=1&host=www.speedtest.net

推荐你用国内的测速试试，比如电信宽带就用电信的测速 http://service.sh.189.cn/service/speed

爱奇艺我家原来也不卡，现在也会有点卡，暂时我无法确定到底是电信的锅还是程序有bug

**Comment by nimotsang** [comment]
好的，我回去再试试，非常感谢您的及时回复。

**Comment by izerosoul** [comment]
经过排查发现使用公共DNS有可能会出现这类问题，请确保你使用了自己宽带运营商的DNS

参考[DNS配置](https://github.com/izerosoul/shadowsocks_erx/wiki/%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
