### ISSUE TITLE
能不能支持域名白名单

### ISSUE THREAD

**Issue by Phil2048** [izerosoul/shadowsocks_erx#33]
能不能支持域名白名单

**Comment by Phil2048** [comment]
steam 默认走代理 每次登录都需要验证  如果登录可以白名单 不走代理  就不需要验证 了

**Comment by izerosoul** [comment]
不支持，只能IP白名单。
域名白名单的话需要弄另外一套方案，以前在别的路由上弄过，我觉得效果不够稳定，所以没有实现
