### ISSUE TITLE
我想咨询一下pcre如何编译？

### ISSUE THREAD

**Issue by landvd** [izerosoul/shadowsocks_erx#4]
以前编译过SS 2.6版，后来由于更新系统，编译环境删除了。这几天应坛友之约编译ERL的SS，环境和之前的一样，就是pcre现在无法编译通过，提示
./.libs/libpcre.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
Makefile:1438: recipe for target 'libpcrecpp.la' failed
make[1]: *** [libpcrecpp.la] Error 1
make[1]: Leaving directory '/home/dvd/pcre-8.41'
Makefile:1322: recipe for target 'all' failed
make: *** [all] Error 2
如果允许的话，可否编译一份mips和mipsel的pcre邮给我，我的邮箱是:5586822@qq.com。谢

**Comment by izerosoul** [comment]
可以参考一下这个帖子：
https://www.l68.net/2727.html
