### ISSUE TITLE
如果局域网有两台机器不想走ss如何设置？

### ISSUE THREAD

**Issue by cs57** [izerosoul/shadowsocks_erx#5]
> PT下载用户请注意，如果你有独立的下载机，可以设置让下载机不走SS。具体操作如下：
ss启动脚本/etc/init.d/shadowsocks里面有下面一行:
#BYPASS_RANGE=192.168.123.0/24

是直接BYPASS_RANGE=192.168.1.20/32 192.168.1.30/32吗？

**Comment by izerosoul** [comment]
不行，只能设置一个IP或IP段。
你自己想办法修改脚本吧。
