### ISSUE TITLE
求教，如何 指定 ip 或 域名，不走代理

### ISSUE THREAD

**Issue by love1980s** [izerosoul/shadowsocks_erx#6]
求教，如何 指定 ip 或 域名，不走代理

**Comment by izerosoul** [comment]
注意看说明：
PT下载用户请注意，如果你有独立的下载机，可以设置让下载机不走SS。具体操作如下：
ss启动脚本/etc/init.d/shadowsocks里面有下面一行:
#BYPASS_RANGE=192.168.123.0/24
去掉注释(删掉#号)重启服务就可以生效，然后192.168.123.0/24这整个网段都不会走ss通道了，同时也无法翻墙了，192.168.123.0/24也可以换成单独IP或者其它网段。

**Comment by izerosoul** [comment]
你说源IP还是目的IP？如果是源IP，草考PT用户设置。如果是目的IP，把IP段添加到/config/shadowsocks/conf/chnroute.txt末尾重启服务就可以了

**Comment by love1980s** [comment]
是目的

不走代理的目的域名暂时无法添加？

**Comment by izerosoul** [comment]
是的
