### ISSUE TITLE
ss-monitor 多次重复尝试连接ss-server，会被ss-server自动屏蔽ip

### ISSUE THREAD

**Issue by Haixing-Hu** [izerosoul/shadowsocks_erx#8]
这个ss-monitor的功能应该可以通过配置被禁用，或者可以调节测试周期。

**Comment by izerosoul** [comment]
ss-monitor是个sh脚本，通过检测能否访问google与百度来判断翻墙是否正常&网络是否正常，检测到异常就重启ss服务，并不会直接连接ss服务器。

不使用crontab -e添加计划任务就不会启用

**Comment by Haixing-Hu** [comment]
ss-monitor会定期访问google判断是否翻墙成功，但访问google就会连接ss-server来翻墙；而最新的ss-server中默认增加了防ddos攻击机制，如果发现某个ip在短时间内多次连接翻墙就会封锁该ip，没办法设置白名单，只能重启ss-server（这点在shadowsocks的issue中得到了确认）。所以，要么降低ss-monitor的检查频率，要么增加个选项可以关闭他。我现在没找到哪里调用了他，因为都是二进制文件，只能修改这个脚本把它所有代码都注释掉。自从这么干以后，ss-server再也没有封过我的ip，由此判定问题就是它引发的。
