### ISSUE TITLE
另外源码在哪里？怎么只有二进制版本？

### ISSUE THREAD

**Issue by Haixing-Hu** [izerosoul/shadowsocks_erx#9]

**Comment by izerosoul** [comment]
ss的源码自己去github上找，二进制是我编译了shadowsocks-libev的mipsel版本

**Comment by allenn** [comment]
@izerosoul chinadns修改了那些地方能提供一下PATH么？

**Comment by izerosoul** [comment]
https://github.com/izerosoul/shadowsocks_erx/issues/1

这里我上传过代码哈，可以在git日志中查看我修改的地方

**Comment by wanyancan** [comment]
能否帮忙编译一个mips64的版本？先谢了！！
想接双wan，于是刚搞了一台ER-PoE5的机子，竟然是64位的
Linux ubnt 3.10.20-UBNT #1 SMP Wed Aug 30 02:48:37 PDT 2017 mips64 GNU/Linux


> system type             : UBNT_E100
machine                 : Unknown
processor               : 0
cpu model               : Cavium Octeon+ V0.1
BogoMIPS                : 1000.00
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa                     : mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

> processor               : 1
cpu model               : Cavium Octeon+ V0.1
BogoMIPS                : 1000.00
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 2, address/irw mask: [0x0ffc, 0x0ffb]
isa                     : mips1 mips2 mips3 mips4 mips5 mips64r2
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VCED exceptions         : not available
VCEI exceptions         : not available
